import { Easing } from 'react-native-reanimated';

export const INIT_SPHERE_SIZE = 40;
export const MAIN_SPHERE_COMPRESSED_SCALE = 1;
export const MAIN_SPHERE_EXPANDED_SCALE = 5;

export const MAIN_SPHERE_ANIM_DURATION = 5000;
export const DEFAULT_ANIM_EASING = Easing.quad;

export const SINGLE_SQUEEZE_ANIM_DURATION = 100;

export const COLLIDING_SPHERES_AMOUNT = 140;
export const COLLIDING_SPHERES_IN_RANGE_AMOUNT = 15;
export let COLLIDING_SPHERES_CHUNK_ANIM_DURATION =
  MAIN_SPHERE_ANIM_DURATION /
  (COLLIDING_SPHERES_AMOUNT / COLLIDING_SPHERES_IN_RANGE_AMOUNT);
COLLIDING_SPHERES_CHUNK_ANIM_DURATION =
  // making sure last colliding animation will be over when sphere expansion is
  (MAIN_SPHERE_ANIM_DURATION - COLLIDING_SPHERES_CHUNK_ANIM_DURATION) /
  (COLLIDING_SPHERES_AMOUNT / COLLIDING_SPHERES_IN_RANGE_AMOUNT);
export const COLLIDING_SPHERES_EASING = Easing.linear;
export const COLLIDING_SPHERES_MIN_OFFSET = 600;
export const COLLIDING_SPHERES_OFFSET_RANGE = 300;
